# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import services_pb2 as services__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SovereignMindServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSovereigntyGenome = channel.unary_unary(
                '/sovereignmind.SovereignMindService/GetSovereigntyGenome',
                request_serializer=services__pb2.GenomeRequest.SerializeToString,
                response_deserializer=services__pb2.GenomeResponse.FromString,
                _registered_method=True)
        self.SearchGenomeTraits = channel.unary_unary(
                '/sovereignmind.SovereignMindService/SearchGenomeTraits',
                request_serializer=services__pb2.GenomeSearchRequest.SerializeToString,
                response_deserializer=services__pb2.GenomeSearchResponse.FromString,
                _registered_method=True)
        self.CalculateSimilarity = channel.unary_unary(
                '/sovereignmind.SovereignMindService/CalculateSimilarity',
                request_serializer=services__pb2.SimilarityRequest.SerializeToString,
                response_deserializer=services__pb2.SimilarityResponse.FromString,
                _registered_method=True)
        self.RunConstitutionalEvaluation = channel.unary_unary(
                '/sovereignmind.SovereignMindService/RunConstitutionalEvaluation',
                request_serializer=services__pb2.ConstitutionalRequest.SerializeToString,
                response_deserializer=services__pb2.ConstitutionalResponse.FromString,
                _registered_method=True)
        self.StartSandboxSimulation = channel.unary_stream(
                '/sovereignmind.SovereignMindService/StartSandboxSimulation',
                request_serializer=services__pb2.SandboxRequest.SerializeToString,
                response_deserializer=services__pb2.SandboxTick.FromString,
                _registered_method=True)
        self.DraftEmergencyContract = channel.unary_unary(
                '/sovereignmind.SovereignMindService/DraftEmergencyContract',
                request_serializer=services__pb2.ProcurementRequest.SerializeToString,
                response_deserializer=services__pb2.ProcurementResponse.FromString,
                _registered_method=True)
        self.OptimizePrompt = channel.unary_unary(
                '/sovereignmind.SovereignMindService/OptimizePrompt',
                request_serializer=services__pb2.PromptOptimizeRequest.SerializeToString,
                response_deserializer=services__pb2.PromptOptimizeResponse.FromString,
                _registered_method=True)


class SovereignMindServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetSovereigntyGenome(self, request, context):
        """Sovereignty Genome Engine
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchGenomeTraits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateSimilarity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunConstitutionalEvaluation(self, request, context):
        """Autonomous Constitutional AI Layer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSandboxSimulation(self, request, context):
        """Synthetic Civilization Sandbox
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DraftEmergencyContract(self, request, context):
        """Emergency Contracting Autopilot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OptimizePrompt(self, request, context):
        """Self-Improving Agent Loop / Autonomous Prompt Optimization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SovereignMindServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSovereigntyGenome': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSovereigntyGenome,
                    request_deserializer=services__pb2.GenomeRequest.FromString,
                    response_serializer=services__pb2.GenomeResponse.SerializeToString,
            ),
            'SearchGenomeTraits': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchGenomeTraits,
                    request_deserializer=services__pb2.GenomeSearchRequest.FromString,
                    response_serializer=services__pb2.GenomeSearchResponse.SerializeToString,
            ),
            'CalculateSimilarity': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateSimilarity,
                    request_deserializer=services__pb2.SimilarityRequest.FromString,
                    response_serializer=services__pb2.SimilarityResponse.SerializeToString,
            ),
            'RunConstitutionalEvaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.RunConstitutionalEvaluation,
                    request_deserializer=services__pb2.ConstitutionalRequest.FromString,
                    response_serializer=services__pb2.ConstitutionalResponse.SerializeToString,
            ),
            'StartSandboxSimulation': grpc.unary_stream_rpc_method_handler(
                    servicer.StartSandboxSimulation,
                    request_deserializer=services__pb2.SandboxRequest.FromString,
                    response_serializer=services__pb2.SandboxTick.SerializeToString,
            ),
            'DraftEmergencyContract': grpc.unary_unary_rpc_method_handler(
                    servicer.DraftEmergencyContract,
                    request_deserializer=services__pb2.ProcurementRequest.FromString,
                    response_serializer=services__pb2.ProcurementResponse.SerializeToString,
            ),
            'OptimizePrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimizePrompt,
                    request_deserializer=services__pb2.PromptOptimizeRequest.FromString,
                    response_serializer=services__pb2.PromptOptimizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sovereignmind.SovereignMindService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sovereignmind.SovereignMindService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SovereignMindService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSovereigntyGenome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereignmind.SovereignMindService/GetSovereigntyGenome',
            services__pb2.GenomeRequest.SerializeToString,
            services__pb2.GenomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchGenomeTraits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereignmind.SovereignMindService/SearchGenomeTraits',
            services__pb2.GenomeSearchRequest.SerializeToString,
            services__pb2.GenomeSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateSimilarity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereignmind.SovereignMindService/CalculateSimilarity',
            services__pb2.SimilarityRequest.SerializeToString,
            services__pb2.SimilarityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunConstitutionalEvaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereignmind.SovereignMindService/RunConstitutionalEvaluation',
            services__pb2.ConstitutionalRequest.SerializeToString,
            services__pb2.ConstitutionalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSandboxSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sovereignmind.SovereignMindService/StartSandboxSimulation',
            services__pb2.SandboxRequest.SerializeToString,
            services__pb2.SandboxTick.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DraftEmergencyContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereignmind.SovereignMindService/DraftEmergencyContract',
            services__pb2.ProcurementRequest.SerializeToString,
            services__pb2.ProcurementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OptimizePrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereignmind.SovereignMindService/OptimizePrompt',
            services__pb2.PromptOptimizeRequest.SerializeToString,
            services__pb2.PromptOptimizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
